angular/flex-layout

.editorconfig
.gitignore

* Ignores `vscode` in gitignore
* Adds an editorconfig with the https://github.com/angular/angular settings

chore(config): update development configs

---

LICENSE

* Bumps the year in the license (similar as in angular/angular)
**Note**: Difficult PR, so please don't review it to harsh ;)

chore: bump year in license

---

src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/api/layout-gap.ts
src/lib/utils/testing/helpers.ts

Resolves tslint errors currently failing the Travis build for master

chore(lint): resolve tslint errors in master

---

.travis.yml
package.json
tools/gulp/tasks/unit-test.ts
tools/scripts/ci/build-and-test.sh
tools/test/browser-providers.ts
tools/test/karma.config.ts
yarn.lock

* Properly reports exit codes of the unit tests to Travis
* Updates Karma version
* Uses Yarn Installation from Travis CI container
* Runs Unit tests now against the latest Chrome & Firefox versions.
* Made the required tests less, so the tests finish quicker and run more stable.

build: cleanup travis ci setup

---

package.json
tools/scripts/release/npm_assets/package.json

Update `peerDependencies` to RxJS final to align with Angular, and avoid errors while `npm install`.
The `yarn.lock` file may need to be updated too, but not sure how to do that in a clean way and it's not required for a new npm release.
Fixes #117

(feat) Update to RxJS final

---

package.json
release
tools/scripts/release/npm_assets/package.json

*  Fix incorrect version num(s) in package.json files (in current master branch).
*  update release script to update package.json version # in the **master** branch

update(release): fix release script to update package.json files

---

release

chore(release): do not save the local release branch, only the tag

---

src/demo-app/app/demo-app-module.ts
src/demo-app/app/demo-app/demo-app.ts
src/demo-app/app/docs-layout-responsive/DemosResponsiveLayouts.ts
src/demo-app/app/docs-layout-responsive/responsiveFlexDirective.demo.ts
src/demo-app/app/docs-layout-responsive/responsiveFlexOrder.demo.ts
src/demo-app/app/docs-layout-responsive/responsiveLayoutDirections.demo.ts
src/demo-app/app/docs-layout-responsive/responsiveShowHide.demo.ts
src/demo-app/app/docs-layout-responsive/responsiveStyle.demo.ts
src/demo-app/app/github-issues/DemosGithubIssues.ts
src/demo-app/app/github-issues/issue.135.demo.ts
src/demo-app/app/github-issues/issue.181.demo.ts
src/demo-app/app/github-issues/issue.197.demo.ts
src/demo-app/app/shared/media-query-status.ts
src/demo-app/app/shared/shared.module.ts

* create **`<media-query-status>`** view component
* used SharedModule for shared imports and declarations
* simplify demos by using the **MediaQueryStatus** component
* improve layout within the md-tool-bar header area

fix(demo): improve use of ObservableMedia service

---

src/demo-app/app/demo-app/demo-app.css
src/demo-app/app/docs-layout-responsive/_module.ts
src/demo-app/app/docs-layout/_module.ts
src/demo-app/app/github-issues/_module.ts
src/demo-app/app/github-issues/issue.181.demo.ts
src/demo-app/app/github-issues/issue.266.demo.css
src/demo-app/app/github-issues/issue.266.demo.ts
src/demo-app/app/github-issues/splitter/split-area.directive.ts
src/demo-app/app/github-issues/splitter/split-handle.directive.ts
src/demo-app/app/github-issues/splitter/split.component.scss
src/demo-app/app/github-issues/splitter/split.directive.ts
src/demo-app/app/github-issues/splitter/split.module.ts
src/demo-app/app/shared/_module.ts
src/demo-app/app/stack-overflow/_module.ts
src/lib/flexbox/api/base.ts
src/lib/flexbox/api/flex.spec.ts
src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/index.ts
src/lib/media-query/observable-media.ts
src/lib/utils/style-transforms.spec.ts
src/lib/utils/style-transforms.ts

* support DI of flexbox/api Directive classes
* implement Directive method `activatedValue` getter/setter
* to imperatively read current activated input value
* to write API values with immediate style updates
* implement demo using splitters (ngxSplit) with fxLayout and fxFlex layouts
> Based on issues and ideas by @amcdnl + [ngx-u](https://github.com/swimlane/ngx-ui)
Fixes #266.

fix(lib): support API directive queries

---

src/demo-app/app/docs-layout/layoutAlignment.demo.html
src/lib/api/flexbox/layout-align.spec.ts
src/lib/api/flexbox/layout-align.ts

Thx to @spottedmahn for original PR and work.
Closes #404.

update(api, layoutAlign): add 'space-evenly' as a main-axis option

---

CONTRIBUTING.md

chore: add CONTRIBUTING guidelines

---

docs/documentation/Background.md
docs/documentation/Browser-Support.md
docs/documentation/Home.md
docs/documentation/Responsive-API.md
docs/documentation/fxFlex-API.md

* Replace HTML in the docs with Markdown
* Add description to links

chore(docs): replace image HTML with Markdown syntax

---

tools/tslint-rules/deletionTargetRule.ts
tslint.json

* Equivalent commit to angular/material2#9881

build: add tslint rule to enforce deletion targets

---

docs/documentation/Developer-Setup.md
docs/documentation/Live-Demos.md
package-lock.json
package.json
src/apps/universal-app/package-lock.json
src/lib/bidi/README.md
src/lib/server/README.md
tools/gulp/tasks/universal.ts

* Add details about building the Universal app to the Wiki
* Add README files to the server and Bidi directories to explain
their purposes
* Remove unused `@angular/tsc-wrapped`
* Add Universal app serve task

docs: add Universal app changes to documentation

---

src/apps/demo-app/package-lock.json
src/lib/core/match-media/match-media-provider.ts
src/lib/core/module.ts
src/lib/extended/module.ts
src/lib/flex/flex/flex.ts
src/lib/flex/module.ts
tools/gulp/tasks/development.ts

* fix an issue where when fxFlex value is blank, the max-width
would be set to the default flex (1e-9px)
* move server utils into the Core module since all modules import
the core module
* fix demo app serve method to rebuild the demo app correctly

fix(fxFlex): make sure not to set width/height when flex is default

---

docs/documentation/Performance-Considerations.md
docs/documentation/fxLayoutGap-API.md

docs: fix broken links

---

src/apps/demo-app/src/polyfills.ts

fix(demo-app): add polyfills for IE11 to demo-app

---

src/apps/demo-app/package-lock.json
src/apps/demo-app/src/app/app.module.ts
src/lib/module.ts

* Add a custom breakpoint in the demo-app to ensure it works with
AOT
* Deprecate the `provideBreakPoints` static method on the main
module

feat(demo-app): use/register custom breakpoints

---

src/lib/core/breakpoints/break-point-registry-provider.ts
src/lib/core/module.ts

* Fix issue with breakpoints not activating because the new
breakpoints token is emptied when BreakPointRegistry is
injected again

fix(breakpoints): add global provider for BreakPointRegistry

---

src/apps/demo-app/src/app/app.component.html
src/apps/demo-app/src/app/app.component.ts

feat(demo-app): add version number to header

---

src/lib/module.ts

chore: add descriptive comment for FlexLayoutModule

---

package.json

Equivalent to angular/material2#12230

build: add git-semver-tags to dev dependencies

---

src/lib/core/breakpoints/data/break-points.ts

fix: use correct xl breakpoint

---

src/lib/core/media-marshaller/media-marshaller.ts

fix(core): avoid race condition between registration and activation

---

.gitignore
package.json
src/lib/core/match-media/mock/mock-match-media.ts
src/lib/core/match-media/server-match-media.ts
yarn.lock

build: upgrade to Angular v7.2 and TypeScript v3.2

---

src/apps/demo-app/src/app/github-issues/split/split-handle.directive.ts
src/apps/demo-app/src/app/github-issues/split/split.directive.ts

docs: make splitter work in IE

---

package.json
src/apps/demo-app/src/app/app.module.ts
src/apps/demo-app/src/app/stack-overflow/hide-custom-bp/hide-custom-bp.component.scss
src/apps/demo-app/src/app/stack-overflow/hide-custom-bp/hide-with-custom-bp.component.ts
src/apps/demo-app/src/app/stack-overflow/stack-overflow.module.ts
src/apps/demo-app/src/app/stack-overflow/stack-overflow/stack-overflow.component.ts
src/apps/demo-app/src/styles.scss
yarn.lock

Add demo showing custom breakpoint working with `fxHide.yba-min-height`
Closes #961.

fix(extended): add demo to show fxHide with used with custom breakpoint

---

src/lib/core/breakpoints/data/orientation-break-points.spec.ts
src/lib/core/match-media/match-media.spec.ts
src/lib/core/match-media/match-media.ts
src/lib/core/match-media/mock/mock-match-media.spec.ts
src/lib/core/media-marshaller/media-marshaller.spec.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/extended/class/class.spec.ts
src/lib/extended/img-src/img-src.spec.ts
src/lib/extended/show-hide/hide.spec.ts
src/lib/extended/show-hide/show.spec.ts
src/lib/extended/style/style.spec.ts
src/lib/flex/flex-order/flex-order.spec.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout/layout.spec.ts
src/lib/grid/align-columns/align-columns.spec.ts
src/lib/grid/align-rows/align-rows.spec.ts
src/lib/grid/area/area.spec.ts
src/lib/grid/areas/areas.spec.ts
src/lib/grid/auto/auto.spec.ts
src/lib/grid/column/column.spec.ts
src/lib/grid/columns/columns.spec.ts
src/lib/grid/gap/gap.spec.ts
src/lib/grid/grid-align/grid-align.spec.ts
src/lib/grid/row/row.spec.ts
src/lib/grid/rows/rows.spec.ts
src/lib/server/server-provider.ts

* improve use of inject() in tests

 test(ssr): fix SSR flakes and change matchMedia variable name

---

src/lib/package.json

build: add `@angular/platform-browser` as a peer dep

---

package-lock.json
src/lib/extended/class/class.ts
src/lib/extended/img-src/img-src.ts
src/lib/extended/module.ts
src/lib/extended/show-hide/show-hide.ts
src/lib/extended/style/style.ts
src/lib/flex/flex-align/flex-align.ts
src/lib/flex/flex-offset/flex-offset.ts
src/lib/flex/flex-order/flex-order.ts
src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.ts
src/lib/flex/layout-gap/layout-gap.ts
src/lib/flex/layout/layout.ts
src/lib/flex/module.ts
src/lib/grid/align-columns/align-columns.ts
src/lib/grid/align-rows/align-rows.ts
src/lib/grid/area/area.ts
src/lib/grid/areas/areas.ts
src/lib/grid/auto/auto.ts
src/lib/grid/column/column.ts
src/lib/grid/columns/columns.ts
src/lib/grid/gap/gap.ts
src/lib/grid/grid-align/grid-align.ts
src/lib/grid/module.ts
src/lib/grid/row/row.ts
src/lib/grid/rows/rows.ts

Ref https://github.com/angular/angular/issues/31956

build: add Directive decorators and export all base classes

---

.circleci/config.yml
package.json
src/apps/demo-app/package.json
src/apps/hello-world/package.json
src/apps/universal-app/package.json
src/lib/grid/auto/auto.spec.ts
tools/gulp/tasks/universal.ts
yarn.lock

See angular/angular/pull/33348
Fixes #1079

build: fix gulp setup not working with node v12

---

docs/documentation/_Sidebar.md

[How Flexbox Works - Explained] URL is broken

Broken Url

---

src/lib/core/media-trigger/media-trigger.ts

build: add missing return type for strict mode

---

src/lib/core/media-marshaller/print-hook.ts

This patches a potential memory leak in the PrintHook service
where beforeprint and afterprint events where added but never
removed.
Fixes #1212

fix(print-hook): unregister event listeners on destroy

---

src/lib/extended/show-hide/show-hide.ts
src/lib/extended/show-hide/show.spec.ts

Reverts angular/flex-layout#1243

Revert "fix(show-hide): use initial value as fallback instead of parent"

---

.github/ISSUE_TEMPLATE/Bug.md
CONTRIBUTING.md
README.md

Update StackBlitz links to use the latest version of Angular and
Angular Layout.

chore: update StackBlitz links

---

package.json
stylelint-config.json
yarn.lock

Update the stylelint config file to use unit-allowed-list

build: update stylelint usage to use unit-allowed-list

---

scripts/saucelabs/start-tunnel.sh

Update the version of the sauceconnect binary used to the latest
version.

ci: update sauceconnect verstion to 4.6.2

---

src/lib/core/media-marshaller/print-hook.ts

Fixes https://github.com/angular/flex-layout/issues/1324

Fix SSR build: check null _document.defaultView

---

src/lib/grid/public-api.ts

build: export grid directives

---

.gitignore
.prettierrc.js
docs/documentation/mediaObserver.md

Update mediaObserver documentation - this supercedes #1350

Media observer docs

---

src/lib/package.json

build: allow for rxjs v7 usage
