.travis.yml
package.json
tools/scripts/ci/after-success.sh

* Updates the travis-after-modes script to the latest version (fixed potential travis timeouts)
* Fixed a wrong path to the `after-success.sh` script.
R: @ThomasBurleson

chore: fix per-commit publishing for travis

---

tools/scripts/release/publish-build-artifacts.sh

When retrieving the last commit message, the script currently pipes it through the `head` command.
Since the `git log` command using the `less` command will exit immediately the pipe will fail with a `141` exit code (because it can't read from a closed stream)

chore: fix sigpipe error for commit message

---

src/lib/package.json

* Fixes inconsistent release packaging between `@angular/{core,material}`

chore: es5 modules as entry point

---

README.md

Set of terms proposed/updated:
- Angular Flex Layout (or just Flex Layout) - used in general context. Neither Angular Flexbox Layout nor Flex-Layout
- Flex Layout API - used in more technical context, when we use code samples
- Flexbox (not FlexBox)
It would be nice to update the Wiki page accordingly

Consistent naming / terms usage

---

tools/scripts/release/npm_assets/package.json

* Fixes the incorrect path for the UMD bundles, which is essential for all module loaders and bundlers like Webpack.

chore: fix incorrect path to umd bundles

---

package.json
yarn.lock

Right now Travis tries to publish the build artifacts to the `flex-layout-builds` repository for each mode.
Fortunately it still only published once, because Git doesn't allow re-publishing of the same git tags.
The issue has been fixed with version `0.0.7` of `travis-after-modes` (DevVersion/travis-after-modes@387328e)
This is similar to angular/material2@8470534

chore: only publish artifacts once

---

src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/api/layout-gap.ts
src/lib/utils/testing/helpers.ts

Use margin-top for column layouts instead of margin-left.
Also add small typing improvement to the queryFor helper function.

Apply margin-top in layout-gap for column layouts - Fixes #106

---

src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/api/layout-gap.ts

* fxLayoutGap not applied to children inserted after initial render
Fixes #95.

fix(fxLayoutGap): add gaps to dynamic content

---

src/lib/flexbox/api/flex.spec.ts
src/lib/flexbox/api/flex.ts

* for cases where the flex-basis === "auto", use the specified or default values of shrink and grow.
* add tests for flex-bases == "auto", "none", "initial", "noshrink", and "nogrow"
Fixes #120.

fix(fxFlex): fix use of values with 'auto'

---

src/demo-app/app/docs-layout-responsive/responsiveRowColumns.demo.ts
src/lib/flexbox/api/base.ts
src/lib/flexbox/api/flex-align.ts
src/lib/flexbox/api/flex-offset.ts
src/lib/flexbox/api/flex-order.ts
src/lib/flexbox/api/flex.ts
src/lib/flexbox/api/hide.spec.ts
src/lib/flexbox/api/hide.ts
src/lib/flexbox/api/layout-align.ts
src/lib/flexbox/api/layout-gap.ts
src/lib/flexbox/api/layout-wrap.ts
src/lib/flexbox/api/layout.ts
src/lib/flexbox/api/show.spec.ts
src/lib/flexbox/api/show.ts
src/lib/utils/testing/helpers.ts

* Many directive selectors were missing a `,` separator between the breakpoint-enabled selectors. 
>  xs and gt-xs selectors were not delimited.
* **fxShow**, **fxHide** preserve and restore the element's original display CSS style
* added more tests standalone breakpoint selectors, disabled selectors, and deactivated mediaQueries
* The **fxHide** and **fxShow** should not change the display mode to `flex`. Instead
the display mode (when not `none`) should be the default (=== `block`) or the explicitly assigned display mode for that element.
fixes #62, fixes #105, closes #59.

fix(fxHide,fxShow): fix standalone breakpoint selectors

---

src/lib/flexbox/api/base.ts
src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/api/layout-gap.ts
src/lib/flexbox/responsive/responsive-activation.ts
src/lib/utils/testing/helpers.ts

fxLayoutGap should consider (and skip) hidden elements when applying layout-gap logic.
fixes #136.

fix(fxLayoutGap): skip hidden element nodes

---

src/lib/media-query/index.ts

After upgrade to beta 4,  I can't import `ObservableMediaService` from the barrel.
fixes #144.

fix(build): add observable-media-service to index.ts

---

tools/test/browser-providers.ts

Fix tests for SauceLabs and BrowerStack testing:
* fix SauceLabs to test **IE 11** on Windows 10
* *disable* failing **Safari 10** testing (MacOS Sierra)

chore(travis): fix browser provider config

---

src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/api/layout-gap.ts

*  `margin-right` be used with `fxLayout="row" fxLayoutWrap fxLayoutGap` combinations
*  `margin-bottom` be used with `fxLayout="column" fxLayoutWrap fxLayoutGap` combinations
fixes #108

fix(fxLayoutGap): consider fxLayoutWrap to apply gap logic

---

src/lib/media-query/breakpoints/break-points.ts

* alias `xl` now has mediaQuery == `screen and (min-width: 1920px) and (max-width: 5000px)`
fixes #149.

fix(breakpoints): resolve 1px hole between lg -> xl breakpoints

---

src/demo-app/app/demo-app-module.ts
src/demo-app/app/docs-layout-responsive/DemosResponsiveLayouts.ts
src/lib/flexbox/_module.ts
src/lib/flexbox/api/flex.spec.ts
src/lib/flexbox/api/hide.spec.ts
src/lib/flexbox/api/layout-align.spec.ts
src/lib/flexbox/api/layout-gap.spec.ts
src/lib/flexbox/api/layout.spec.ts
src/lib/flexbox/api/show.spec.ts
src/lib/media-query/_module.ts

Previously releases used FlexLayoutModule.forRoot(). This has been deprecated and removed.
-*before*-
```js
@NgModule({
declarations : [...],
imports : [
CommonModule,
FlexLayoutModule.forRoot()
]
})
export class DemosResponsiveLayoutsModule { }
```
-*after*-
```js
@NgModule({
declarations : [...],
imports : [ CommonModule, FlexLayoutModule ]
})
export class DemosResponsiveLayoutsModule { }
```

fix(api): remove use of static ngModule.forRoot()

---

src/demo-app/app/demo-app/demo-app.css
src/demo-app/app/docs-layout-responsive/DemosResponsiveLayouts.ts
src/demo-app/app/docs-layout-responsive/responsiveStyle.demo.ts
src/lib/flexbox/_module.ts
src/lib/flexbox/api/base-adapter.spec.ts
src/lib/flexbox/api/base-adapter.ts
src/lib/flexbox/api/class.spec.ts
src/lib/flexbox/api/class.ts
src/lib/flexbox/api/show.spec.ts
src/lib/flexbox/api/style.spec.ts
src/lib/flexbox/api/style.ts
src/lib/media-query/mock/mock-match-media.ts

@ThomasBurleson - The new PR is ready for reviewing

feat(api): add responsive support for ngClass and ngStyle

---

src/lib/flexbox/api/flex.spec.ts
src/lib/flexbox/api/flex.ts

handle various scenarios of grow/shrink being zero:
*  set `min-width`/`min-height` only if `grow != 0`
*  set `max-width`/`max-height` only if `shink != 0`
*  set both min and max if both `grow == 0` AND `shink == 0`
*  add tests for these scenarios
*  remove max-width from  test "should set a min-width when the shrink == 0"
fixes #153
Signed-off-by: Somo <somo@mombo.solutions>

fix(fxFlex): prevent setting min/max-size when grow/shrink is zero

---

src/lib/flexbox/api/base-adapter.ts
src/lib/flexbox/api/style.ts

* update `BaseFxDirectiveAdapter::cacheIput()` to support cacheRaw options
* fix failing style.spec.ts tests

fix(fxStyle): enable raw input caching

---

CHANGELOG.md
package.json
src/demo-app/app/docs-layout/DemosLayoutAPI.ts
src/lib/flexbox/_module.ts
tools/scripts/release/npm_assets/README.md

* 'forRoot()' fn is never evaluated in AoT, ngc only analyzes the content of the fn to get the module and ngc does not know what to do with the first statetement (console.warn)
* clarify changes to FlexLayoutModule.forRoot()
Refs http://github.com/angular/angular#14410
Fixes #174, Fixes #175, Fixes #176, Fixes #178.

fix(FlexLayoutModule): remove console.warn() calls that conflict with ngc+aot

---

src/lib/flexbox/api/show-hide.ts
src/lib/media-query/match-media.spec.ts
src/lib/media-query/mock/mock-match-media.ts
src/lib/media-query/observable-media-service.spec.ts
src/lib/media-query/observable-media-service.ts

**ObservableMedia** reports of the active breakpoint are not consistent:
*  during page startup - active breakpoint as "gt-sm"  instead of "md", "lg", or "xl".
*  during manual resize - active breakpoint as "xs", "sm", "md", "lg", or "xl".
ObservableMedia should not (by default) report `gt-<xxx>` activations.
fixes #185.

fix(ObservableMedia): provide consistent reporting of active breakpoint

---

package.json
src/demo-app/app/docs-layout-responsive/DemosResponsiveLayouts.ts
src/demo-app/app/github-issues/DemosGithubIssues.ts
src/demo-app/app/github-issues/issue.135.demo.ts
src/lib/flexbox/api/flex.spec.ts
src/lib/flexbox/api/flex.ts
src/lib/utils/testing/custom-matchers.ts

Layout changes from gt-sm will not restore default layout with auto
fixes #135.

fix(fxFlex): fxFlex=auto with overlapping breakpoints activated

---

src/lib/flexbox/api/base.ts
src/lib/flexbox/api/flex.spec.ts
src/lib/utils/testing/custom-matchers.ts
src/lib/utils/testing/dom-tools.ts

**flex-layout** uses private APIs from @angular/core. These apis are no longer available in A4.
Fixes #193.

fix(build): remove use of Angular private API 

---

package.json
src/demo-app/app/github-issues/DemosGithubIssues.ts
src/demo-app/app/github-issues/issue.197.demo.ts
src/lib/flexbox/api/class.spec.ts
src/lib/flexbox/api/class.ts
src/lib/flexbox/api/style.spec.ts
src/lib/flexbox/api/style.ts
src/lib/utils/index.ts
src/lib/utils/style-transforms.spec.ts
src/lib/utils/style-transforms.ts
src/lib/utils/testing/custom-matchers.ts

* Add use of **DomSanitizer** + **SecurityContext.STYLE** to safeguard all style values
* Deprecated use of `style` selectors to favor `ngStyle` selectors since the functionality extends **NgStyle** directive.
* Deprecated use of `class` selectors to favor `ngClass` selectors since the functionality extends **NgClass** directive.
* `ngStyle` restores default (non-activated) inline styles when breakpoint deactivates
* `ngStyle` merges default inline styles with activated styles
* `ngStyle` selectors support Object notations or raw strings (ala html inline styles)
*  e.g. Object notation = `[ngStyle]="{'font-size.px': 10, color: 'rgb(0,0,0)', 'text-align':'left'}"`
*  e.g. Raw-string notation = `style="font-size:10px; color:black; text-align:left;"`
*  NOTE: delimiters for raw-strings must …

fix(ngStyle, ngClass): StyleDirective security fixes & merge activated styles

---

src/demo-app/app/demo-app/demo-app.ts

it is a very confusing mention of a directive that is not actually used in this demo.
Additionally, looks like setting this on router root is a practice likely to change (see https://github.com/angular/material2/issues/1719)

chore(demo): remove unnecessary attributes

---

src/lib/flexbox/api/class.spec.ts
src/lib/flexbox/api/class.ts

*  add missing static `ngClass` and `class`  selectors
*  add tests to demonstrate fallbacks to static selector values
Refs #206

fix(ngClass): add ngClass selector support

---

src/lib/flexbox/api/base-adapter.spec.ts
src/lib/flexbox/api/base-adapter.ts
src/lib/flexbox/api/base.ts
src/lib/flexbox/api/class.spec.ts
src/lib/flexbox/api/class.ts
src/lib/flexbox/api/style.ts

* fix(ngClass):  properly differentiate between `ngClass` and `class` api usages
*  `class.<xxx>` are destructive overrides (as seen in `NgClass::klass`)
*  `ngClass.<xxx>` use iterables to merge/enable/disable 0...n classes
* fix(ngClass,ngStyle): support ChangeDetectionStrategy.OnPush
* Add support for both **OnPush** change detection strategies and for @Input changes.
>  @see https://plnkr.co/edit/jCICQ1GXFnzFqFTFlXwh?p=preview
fixes #206, fixes #215.

fix(ngClass,ngStyle): support proper API usages and ChangeDetectionStrategy.OnPush strategies

---

src/lib/flexbox/api/layout-align.spec.ts
src/lib/flexbox/api/layout-align.ts

Current API translates `start` and `end` to `flex-start` and `flex-end` respectively.
The API should also support the raw `flex-<xxx>` values.
Fixes #232.

fix(fxLayoutAlign): support flex-start and flex-end options

---

src/lib/flexbox/api/base.ts
src/lib/utils/auto-prefixer.spec.ts
src/lib/utils/auto-prefixer.ts

With the following changes the layout of our application works in iOS8

Improve flex css prefixes

---

src/lib/utils/auto-prefixer.ts

parseInt requires two arguments within Google (the second is the radix)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt:
"Always specify this parameter"
Casting with Number('1') is better.

fix(closure-compiler): use Number to cast

---

src/lib/flexbox/api/flex.spec.ts
src/lib/utils/auto-prefixer.spec.ts
src/lib/utils/auto-prefixer.ts

Internal AutoPrefixer updated based on output from prefix rules for n-2 evergreen browsers.
* Updated based on output from https://autoprefixer.github.io/
* Removed Mozilla Firefox prefixes as not required for the evergreen browser
* Remove support for IE10 prefixes (`-ms-`); as only IE 11 and Edge are supported
* Remove support for `-webkit-box` required for OLD iOS , Safari 3, BB7
* Fix value transforms for flex-related keys
Fixes #282

fix(auto-prefixer): resolve perf impacts as reported by LightHouse

---

src/demo-app/app/docs-layout/flexOffetValues.demo.ts
src/demo-app/app/docs-layout/flexOtherValues.demo.ts

I spotted a few inconsistencies between the html and the text being displayed.

Fix demo page to display fxFlex in place of "flex"

---

src/lib/flexbox/api/base.ts

- Prevents a possible TypeError being thrown at `value.trim()` if display is undefined.
- Defaults to `block`, the default display property for css container elements.
Closes #300

fix(flexbox): Add default display property to `getDisplayStyle()`

---

src/demo-app/app/shared/media-query-status.ts
src/lib/media-query/breakpoints/break-point-registry.ts
src/lib/media-query/match-media.spec.ts
src/lib/media-query/match-media.ts
src/lib/media-query/media-monitor.ts
src/lib/media-query/observable-media-provider.ts
src/lib/media-query/observable-media.ts

ObservableMedia only dispatches notifications for activated, non-overlapping breakpoints.
If the MatchMedia lastReplay value is an *overlapping* breakpoint
(e.g. `lt-md`, `gt-lg`) then that value will be filtered by ObservableMedia
and not be emitted to subscribers.
* MatchMedia breakpoints registration was not correct
*  overlapping breakpoints were registered in the wrong order
* non-overlapping breakpoints should be registered last; so the BehaviorSubject's last replay value should be an non-overlapping breakpoint range.
* Optimize stylesheet injection to group `n` mediaQuerys in a single stylesheet
> ![screen shot 2017-06-12 at 1 44 43 pm](https://user-images.githubusercontent.com/210413/27049606-70137f72-4f75-11e7-9ad7-c8d4bbcd5533.png)
Fixes #245, #275, #303.
> See working plunker: …

fix(ObservableMedia): startup should propagate lastReplay value properly

---

package.json

The supported version of node.js has been increased to v8.x by this PR.
Fixes #357

build(npm): update node compability up to `v8.x`

---

.travis.yml
package.json
scripts/ci/travis-testing.sh
scripts/closure-compiler/build-devapp-bundle.sh
src/lib/flexbox/api/base.ts
src/lib/flexbox/api/layout-gap.ts
src/lib/media-query/match-media.ts
src/lib/media-query/mock/mock-match-media.ts
src/universal-app/app/responsive-app.css
src/universal-app/app/responsive-app.ts
src/universal-app/app/splitter/split-area.directive.ts
src/universal-app/app/splitter/split-handle.directive.ts
src/universal-app/app/splitter/split.component.scss
src/universal-app/app/splitter/split.directive.ts
src/universal-app/app/splitter/split.module.ts
src/universal-app/app/util/helper.ts
src/universal-app/index.html
src/universal-app/main.ts
src/universal-app/prerender.ts
src/universal-app/tsconfig-build.json
src/universal-app/tsconfig-prerender.json
test/karma-test-shim.js
tools/gulp/gulpfile.ts
tools/gulp/tasks/ci.ts
tools/gulp/tasks/universal.ts

Use getDom() for platform-server/universal fixes.
Now gets document object from platform-browser by DI instead of global.
* Add universal application to packages
Fixes #187, #354. Closes #346.
> Thx to @ardatan for PR #346.

fix(lib, media-query): support angular/universal

---

src/lib/flexbox/api/base.ts
src/lib/flexbox/api/flex.spec.ts
src/lib/flexbox/api/flex.ts

`fxFlex` works best if the parent container has flexbox styles assigned (display, flex-direction, etc.). If not assigned (inline or via stylesheet), then these styles are auto-injected inline on the DOM parent element.
When scanning parent DOM element for flexbox flow direction, first scan the in element's inline style and then scan the computed stylesheet for the `flex-direction` value.
> It is assumed that if the parent element has a `flex-direction` style property set, then the other required properties (display, border-box, etc.)  have also been assigned.
Fixes #272, #364.

fix(flexbox): scan flex-direction in css stylesheet

---

src/lib/media-query/breakpoints/data/break-points.ts

Previous breakpoints defined mediaQueries like `screen and (max-width: 599px)`. This means that
all responsive layouts (using .xs, .sm, etc.) will not print properly since `@media print` is excluded
by the `screen and ...` breakpoint definitions.
Remove all `screen and ` @media prefixes; so the layouts will appear the same on both display and print devices.
Fixes #361.

fix(breakpoints): support print media

---

src/lib/flexbox/api/base.ts
src/lib/flexbox/api/flex-offset.spec.ts
src/lib/flexbox/api/flex-offset.ts
src/lib/flexbox/api/flex.ts
src/lib/flexbox/api/layout-align.ts
src/lib/utils/layout-validator.ts

`fxFlexOffset` assigns inline `margin-left` style; assuming default flow directions == 'row'. If the parent flow direction == 'column', then a `margin-top` should be used.
Also added a subscription to an optional parent element LayoutDirective; which will trigger the FlexOffsetDirective to update the inline styles to match the current flow direction.
> Note: if `fxFlexOffset` is used **without**  a parent flexbox styling (set via css or directive), then a `display:flex; flex-direction:row;` will be auto assigned to the fxFlexOffset host element's parent.
Fixes #328.

fix(fxFlexOffset): use parent flow direction for margin property

---

src/lib/flexbox/api/layout-gap.ts

Inside the ngZone, the mutation observer and _updateWithValue() style changes causes an infinite recursion. MutationObserver handlers should be executed outside the ngZone.
Fixes #329.

fix(fxLayoutGap): mutation observer should run outside the ngZone

---

src/demo-app/app/docs-layout-responsive/responsiveStyle.demo.ts
src/lib/flexbox/api/base-adapter.ts
src/lib/flexbox/api/base.ts
src/lib/flexbox/api/class.ts
src/lib/flexbox/api/flex-align.ts
src/lib/flexbox/api/flex-fill.ts
src/lib/flexbox/api/flex-offset.ts
src/lib/flexbox/api/flex-order.ts
src/lib/flexbox/api/flex.ts
src/lib/flexbox/api/layout-align.ts
src/lib/flexbox/api/layout-gap.ts
src/lib/flexbox/api/layout-wrap.ts
src/lib/flexbox/api/layout.ts
src/lib/flexbox/api/show-hide.ts
src/lib/flexbox/api/style.ts

* Use Renderer2 instead of Renderer
* Do not extend the Angular base directives, but instead inject them into the constructor.
* improve support for future releases of Angular 5
Fixes #326.

refactor(api): use Renderer2 instead of Renderer

---

src/lib/flexbox/api/base.ts
src/lib/flexbox/api/class.ts
src/lib/flexbox/api/flex-align.ts
src/lib/flexbox/api/flex-offset.ts
src/lib/flexbox/api/flex-order.ts
src/lib/flexbox/api/flex.ts
src/lib/flexbox/api/layout-align.ts
src/lib/flexbox/api/layout-wrap.ts
src/lib/flexbox/api/layout.ts
src/lib/flexbox/api/show-hide.ts
src/lib/utils/style-utils.spec.ts
src/lib/utils/style-utils.ts
src/lib/utils/testing/custom-matchers.ts
src/lib/utils/testing/dom-tools.ts
src/lib/utils/testing/helpers.ts
test/karma.conf.js

Previously, the Show/Hide directives would query the `display` style during directive instantiation.
For elements instantiated during `*ngFor`, constructor calls to getComputedStyle() will incorrectly return “” due to failures in queries for styles in CSS stylesheets or inline styles. Deferring these types of queries to the ngOnInit() lifecycle event, enables valid response to queries for both inline styles and stylesheets.
Fixes #310.

fix(api): defer getComputedStyle() calls until ngOnInit phase

---

src/lib/api/core/renderer-adapter.ts
src/lib/api/ext/class.ts
src/lib/api/ext/style.ts

NgClass and NgStyle use Renderer1 instances; which has been deprecated. Instead use Renderer2 and a RendererAdapter.
Thx @mhevery for his solution!
Refs #386. Fixes #398, #408.

fix(api): use only Renderer2 instances

---

src/lib/api/core/base-adapter.ts
src/lib/api/ext/class.spec.ts
src/lib/api/ext/class.ts

The host `class` attribute should be considered static and should not be used as a ClassDirective selector. This means that without associated responsive APIs, the ClassDirective will not be instantiated for elements using only the `class` attribute.
* Use the `class` attribute as a responsive fallback value only.
* Improve support of the ngClass directive for string and object assignments.
Fixes #393.

fix(api, class): remove ‘[class]’ selector

---

LICENSE
src/lib/api/core/base.ts
src/lib/media-query/breakpoints/data/break-points.ts
src/lib/media-query/mock/mock-match-media.spec.ts
src/lib/media-query/observable-media.spec.ts
src/lib/utils/testing/custom-matchers.ts

MatchMedia was not properly announcing XS activations for applications with startup viewports < 600px.
Improve the specificity of the 'xs' media query enables proper MatchMedia notifications at startup.
Fixes #388.

fix(ObservableMedia): properly announce 'xs' activation at startup

---

src/lib/api/ext/img-src.spec.ts
src/lib/api/ext/img-src.ts
src/lib/api/index.ts
src/lib/module.ts

* add responsive API to img[src.md], img[src.lt-lg], img[src.gt-xs], etc.
* skip actions if responsive keys are not defined
*  without responsive keys (`src.<alias>`) defined, the ImgSrcDirective should **fall-through** and not change any attributes or properties on the `img` DOM element. The `img.src` attribute is dynamically set only when responsive keys are defined.
* defaults to `src=""` if not explicitly assigned
* responsive key activation will then assign the activated value to `img.src` attribute.
Closes #366, Fixes #81, Fixes #376.

feat(api): add responsive API for img elements

---

src/demo-app/app/shared/demo-material-module.ts

Angular Material modules no longer have the Md- prefix (now Mat-).

chore: update to use material mat- prefix

---

src/lib/api/flexbox/flex.spec.ts
src/lib/api/flexbox/flex.ts

When applying the default `fxFlex` to an element (e.g. `<div fxFlex></div>`), the `flex-grow` and `flex-shrink` properties will be changed based on the values passed to `fxGrow` and `fxShrink`, respectively. 
Fixes #435.

update(fxFlex): apply fxGrow and fxShrink values 

---

src/lib/api/flexbox/layout.spec.ts
src/lib/utils/layout-validator.ts

Flexbox CSS supports `display:inline-flex` to indicate that the flexbox container should be inline; similar to the `display:inline-block`.
When used with the **fxLayout** API, this fix will support the **inline** option:
*  `fxLayout="row inline"`
*  `fxLayout="column wrap inline"`
Fixes #525.

fix(fxLayout): add support for inline-flex

---

src/lib/utils/style-utils.ts

Second part of #468 : values can be prefixed too.
@ThomasBurleson

fix(css): add prefixed values before standard ones

---

.travis.yml

* Applies a workaround for travis-ci/travis-ci#8836 that fixes the Chrome launch issues. (similar workaround applied on angular/angular)

build: fix chrome headless not starting

---

package-lock.json
package.json

Artifact of #560. - upgrading to ng 5.2.x . 
Getting a whole lot of following warnings. 
```console
npm WARN @angular/cdk@5.0.4 requires a peer of @angular/core@~5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@5.0.4 requires a peer of @angular/common@~5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@5.0.4 requires a peer of @angular/core@~5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@5.0.4 requires a peer of @angular/common@~5.1.1 but none is installed. You must install peer dependencies yourself.
```
ng material 5.1.x is compatible with ng 5.2 indeed and upgrading fixes those warnings.

chore: upgrade Material to 5.1.0

---

package-lock.json
package.json

Address the following warning. 
```console
npm WARN tsickle@0.24.1 requires a peer of typescript@2.4.2 but none is installed. You must install peer dependencies yourself.
```
by upgrading to tsickle 0.26.0

chore(versions): update tsickle to 0.26.0

---

package-lock.json
package.json

Revisiting #584 again.
Address the following warning. 
```console
npm WARN typescript-eslint-parser@1.0.2 requires a peer of typescript@~2.0.3 but none is installed. You must install peer dependencies yourself.
```
by upgrading madge to 3.0.0 .

chore(versions): upgrade madge to 3.0.0

---

src/lib/api/flexbox/layout.spec.ts
src/lib/utils/style-utils.ts

* Domino can be stupid about parsing styles on the server, so
add an additional inline style read for the property value
* Add a test case for nested flex children when parent uses layout
wrap. This will be useful when adding SSR testing mode to ensure
this case is accounted for in the future
Fixes #430

fix(lib): read correct styles during SSR and add test for layout-wrap

---

scripts/ci/travis-testing.sh

* Equivalent commit to angular/material2#9879

build: don't skip master build when only md files have changed

---

src/demo-app/app/docs-layout/_module.ts
src/demo-app/app/docs-layout/layoutRowWithDirection.demo.ts
src/lib/api/flexbox/flex-offset.spec.ts
src/lib/api/flexbox/flex-offset.ts
src/lib/api/flexbox/layout-gap.spec.ts
src/lib/api/flexbox/layout-gap.ts
src/lib/bidi/bidi-module.ts
src/lib/bidi/bidi.md
src/lib/bidi/dir.ts
src/lib/bidi/directionality.spec.ts
src/lib/bidi/directionality.ts
src/lib/bidi/index.ts
src/lib/bidi/public-api.ts
src/lib/module.ts

fix: apply correct RTL margins

---

.travis.yml
scripts/ci/travis-deploy.sh
scripts/ci/travis-env.sh
scripts/ci/travis-script.sh

* Equivalent commit to angular/material2#9949

build: conditional travis build stages

---

tools/tslint-rules/deletionTargetRule.ts

* Equivalent commit to angular/material2#9931

build: enforce that deprecated APIs have a deletion target

---

src/lib/api/flexbox/layout-gap.spec.ts
src/lib/api/flexbox/layout-gap.ts

* Sort the elements by flex order before applying gap stylings
Fixes #608

fix(layout-gap): apply correct gaps based on flex order

---

src/lib/core/browser-provider.ts

Error is: TypeError: Cannot supply flags when constructing one RegExp from another.  
Discussion here: https://stackoverflow.com/questions/37919802/regex-created-with-constructor-not-working-with-safari

Fix RegExp Issue in older versions of Safari

---

src/lib/core/style-utils/style-utils.ts
src/lib/core/stylesheet-map.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts

* Fix for when flex-basis is unitless and 0
* Fix for when no width/height is applied and flex-basis should be
set
* Fix for IE flex-basis with calc values
* Fix for SSR properties set to 0
Fixes #277
Fixes #280
Fixes #323
Fixes #528
Fixes #534

fix(fxFlex): apply correct flex-basis stylings

---

README.md
docs/documentation/Adaptive-Layouts.md
docs/documentation/Use-Cases.md
docs/documentation/Using-Angular-CLI.md
docs/documentation/_Sidebar.md
docs/documentation/fxFlex-API.md
docs/documentation/fxFlexAlign-API.md
docs/documentation/fxFlexFill-API.md
docs/documentation/fxFlexOffset-API.md
docs/documentation/fxFlexOrder-API.md
docs/documentation/fxLayout-API.md
docs/documentation/fxLayoutAlign-API.md
docs/documentation/fxLayoutGap-API.md
docs/documentation/imgSrc-API.md
docs/documentation/ngClass-API.md
docs/documentation/ngStyle-API.md

* update links in the documentation to reflect the updated
directory structure
Fixes #654

docs(lib): update links to reflect library refactor

---

src/apps/demo-app/src/app/github-issues/issue-266/issue-266.component.html
src/lib/flex/flex-offset/flex-offset.spec.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts
tools/gulp/tasks/development.ts

* add flex basis back if either max or min width/height is set
* related: https://github.com/philipwalton/flexbugs#flexbug-11
* fix demo-app height issue with older Safari
* update tests to reflect new behavior
* update port for demo app to work with BrowserStack Local
Fixes #660 
* `fxFlex` now sets the flex basis to the `max-width/height` or `min-width/height` if they are set

fix(fxFlex): fix wrapping in older versions of Safari

---

src/lib/flex/flex-offset/flex-offset.spec.ts
src/lib/flex/flex-offset/flex-offset.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.ts
src/lib/flex/layout-gap/layout-gap.ts
src/lib/flex/layout/layout.ts

* Set the non-wrapping behavior for fxFlex to be 100% instead of
the width/height value
* Set the default value for fxFlex to auto for column and 0% for
row instead of 1e-9px
Fixes #666 
Fixes #481 
Fixes #544 
Fixes #338 
Fixes #314

fix(fxFlex): fix non-wrapping behavior and default fxFlex value

---

src/apps/demo-app/src/app/layout/docs-layout/docs-layout.component.ts
src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.spec.ts
src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.ts
src/apps/demo-app/src/app/layout/layout.module.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout-gap/layout-gap.ts

* Apply negative margin and positive padding as browser-agnostic
hack for grid gutter
* The new feature is activated by appending `grid` to any
`fxLayoutGap` input, e.g.
`fxLayoutGap="10px grid"`
Fixes #134 
Fixes #235 
Fixes #288

feat(fxLayoutGap): add gutter functionality to layout-gap

---

src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout-gap/layout-gap.ts

fix(fxLayoutGap): add proper gaps for reverse dir

---

CHANGELOG.md

* Add the breaking change for the removal of `validateSuffixes` to the CHANGELOG
Fixes #698

docs: add breaking change for validateSuffixes

---

release

* Refactor script to improve style and readability
* Add `--next` option, so now command line options are `--force`
and `--next`, in any order

build: add next target to release script

---

src/lib/grid/gap/gap.spec.ts

In the Chrome, [grid-gap becomes gap since v66](https://www.chromestatus.com/feature/4986266210795520), so need to fix the gap's unit test issue to pass the unit tests

test(grid-gap): fix chrome 66 naming issue

---

tools/package-tools/rollup-globals.ts

* Equivalent commit to angular/material2#11413

build: fix rollup global name in umd bundle

---

src/apps/demo-app/src/app/app.module.ts
src/lib/flex/flex/flex.ts
src/lib/module.ts

fix(module): make withConfig AOT compatible

---

README.md

* The latest release on NPM points to the 6.x release, so these instructions are no longer necessary

chore: remove Angular v6 instructions from README

---

src/lib/core/base/base.ts
src/lib/extended/show-hide/show-hide.ts
src/lib/flex/flex-align/flex-align.ts
src/lib/flex/flex-order/flex-order.ts
src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.ts
src/lib/flex/layout/layout.ts

* remove duplicate initialization calls in most directives
* remove `getDisplayStyle` call from BaseDirective `ngOnInit`
Fixes #761

perf: remove duplicate function calls

---

build-config.js
package.json

Equivalent commit to https://github.com/angular/material2/pull/12089

build: move angular version to package.json

---

scripts/saucelabs/start-tunnel.sh
test/karma-system-config.js
test/karma-test-shim.js
test/karma.conf.js
test/protractor.conf.js

Equivalent PR to angular/material2#11970

build: update testing configuration

---

docs/documentation/fxFlex-API.md

Maybe I'm missing something, but this might be helpful to specify.

docs: Adds note about default unit for fxFlex if none given

---

.gitignore
src/lib/module.ts

I have fixed issue #846 that causes runtime errors when using `withConfig` without providing `breakpoints` parameter.
There is probably a better way to fix this by locating the root cause but this solution should work for now since it is a workaround I use in my application.

fix(module): do not require breakpoints in withConfig

---

docs/documentation/ObservableMedia.md

Updated "essential" to be "essentially" and replaced double-quotes with single-quotes in code examples, just to remain consistent.

docs: fix minor grammer and use single-quotes in examples

---

src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-align/layout-align.ts

The actual implementation doesn't allow the 'space-between' and 'space-around' flex
align-content options (cross-axis). fxLayoutAlign should cover all of them.
Closes #841

fix(fxLayoutAlign): add space-between and space-around options

---

src/lib/core/base/base.ts
src/lib/core/public-api.ts
src/lib/core/style-builder/style-builder.ts
src/lib/flex/flex-align/flex-align.ts
src/lib/flex/flex-fill/flex-fill.ts
src/lib/flex/flex-offset/flex-offset.spec.ts
src/lib/flex/flex-offset/flex-offset.ts
src/lib/flex/flex-order/flex-order.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-align/layout-align.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout-gap/layout-gap.ts
src/lib/flex/layout/layout.spec.ts
src/lib/flex/layout/layout.ts

This change decouples the style-generation from the actual directives, meaning that the library is now composed of the following:
* Directives that respond to inputs and `matchMedia` events
* Style generation providers that return styles when triggered by directives
This allows for end-users or library authors to provide their own unique style generation (even by borrowing or extending our existing library code) for any directive. This is entirely non-mandatory for use of the `BaseDirective`, since the `BaseDirective` need not always use a de-coupled style provider to function.
The canonical example is the following:
```ts
@Injectable()
export class CustomStyleBuilder extends StyleBuilder {
buildStyles(input: string) {
return {
'style1': 'value1',
};
}
}
@NgModule({
...
providers: [ …
```

feat(core): add ability to override style building

---

docs/documentation/fxHide-API.md
docs/documentation/fxShow-API.md

Updated "aliase" to be "alias" and updated "suffices" to be "suffixes".

docs: minor spelling fixes

---

src/lib/core/base/base.ts
src/lib/core/style-builder/style-builder.ts
src/lib/flex/flex-align/flex-align.ts
src/lib/flex/flex-fill/flex-fill.ts
src/lib/flex/flex-offset/flex-offset.spec.ts
src/lib/flex/flex-offset/flex-offset.ts
src/lib/flex/flex-order/flex-order.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-align/layout-align.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout-gap/layout-gap.ts
src/lib/flex/layout/layout.spec.ts
src/lib/flex/layout/layout.ts

feat(core): add memoization to style generation

---

src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts

Enable support for rem units in FlexDirective
Closes #898

feat(flex): add support for rem units

---

.circleci/config.yml
src/lib/core/match-media/mock/mock-match-media.ts
src/lib/core/media-marshaller/media-marshaller.ts
src/lib/extended/show-hide/hide.spec.ts
src/lib/extended/show-hide/show-hide.ts

* Previously, we weren't registering the breakpoints when the
media marshaller started up, which had been done by the old
MediaMonitor. This corrects that
Fixes #915

fix(core): register all breakpoints at startup

---

src/lib/core/base/base2.ts
src/lib/extended/show-hide/show-hide.ts
src/lib/extended/show-hide/show.spec.ts

fix(core): allow for breakpoints with periods in them

---

src/lib/core/base/base2.ts
src/lib/core/media-marshaller/media-marshaller.spec.ts
src/lib/core/media-marshaller/media-marshaller.ts
src/lib/extended/class/class.ts
src/lib/extended/img-src/img-src.ts
src/lib/extended/show-hide/show-hide.ts
src/lib/extended/style/style.ts
src/lib/flex/flex-align/flex-align.ts
src/lib/flex/flex-offset/flex-offset.ts
src/lib/flex/flex-order/flex-order.spec.ts
src/lib/flex/flex-order/flex-order.ts
src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.ts
src/lib/flex/layout-gap/layout-gap.ts
src/lib/flex/layout/layout.ts
src/lib/grid/align-columns/align-columns.ts
src/lib/grid/align-rows/align-rows.ts
src/lib/grid/area/area.ts
src/lib/grid/areas/areas.ts
src/lib/grid/auto/auto.ts
src/lib/grid/column/column.ts
src/lib/grid/columns/columns.ts
src/lib/grid/gap/gap.ts
src/lib/grid/grid-align/grid-align.ts
src/lib/grid/row/row.ts
src/lib/grid/rows/rows.ts

fix(core): clear recent styles after responsive deactivation

---

src/lib/extended/style/style.spec.ts
src/lib/extended/style/style.ts

fix(ngStyle): should work with preexisting styles

---

src/lib/extended/style/style-transforms.spec.ts
src/lib/extended/style/style-transforms.ts
src/lib/extended/style/style.spec.ts

fix(ngStyle): do not truncate URLs

---

src/lib/extended/show-hide/hide.spec.ts
src/lib/extended/show-hide/show-hide.ts

fix(show-hide): account for fxLayout on same element

---

.gitignore
src/lib/core/breakpoints/break-point-registry.spec.ts
src/lib/core/breakpoints/break-point-registry.ts
src/lib/core/breakpoints/break-point.ts
src/lib/core/breakpoints/breakpoint-tools.spec.ts
src/lib/core/breakpoints/breakpoint-tools.ts
src/lib/core/breakpoints/data/break-points.spec.ts
src/lib/core/breakpoints/data/break-points.ts
src/lib/core/breakpoints/data/orientation-break-points.spec.ts
src/lib/core/breakpoints/data/orientation-break-points.ts
src/lib/core/breakpoints/index.ts
src/lib/core/match-media/match-media.spec.ts
src/lib/core/match-media/match-media.ts
src/lib/core/match-media/mock/mock-match-media.spec.ts
src/lib/core/match-media/mock/mock-match-media.ts
src/lib/core/match-media/server-match-media.ts
src/lib/core/media-marshaller/media-marshaller.spec.ts
src/lib/core/media-marshaller/media-marshaller.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/core/media-observer/media-observer.ts
src/lib/extended/class/class.spec.ts
src/lib/extended/show-hide/show.spec.ts
src/lib/flex/flex-offset/flex-offset.spec.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout/layout.spec.ts
src/lib/server/server-provider.ts

Use breakpoint priority as the only sorting/scanning mechanism;
used to ensure correct MediaChange event notifications.
* prioritize breakpoints: non-overlaps hightest, lt- lowest
* consistently sort breakpoints ascending by priority
* highest priority === smallest range
* remove hackery with reverse(), etc.
* memoize BreakPointRegistry findBy lookups
* fix MatchMedia::observe() to support lazy breakpoint registration
* fix fragile logic in MediaMarshaller
* fix breakpoint registration usage
* clarify update/clear builder function callbacks
* fix MediaObserver breakpoint registration usage
Fixes #648, Fixes #426

fix(core): improve use of breakpoint priorities

---

tools/gulp/packages.ts
tools/package-tools/build-bundles.ts
tools/package-tools/build-package.ts
tools/package-tools/build-release.ts
tools/package-tools/rollup-globals.ts

build: UMD module references incorrect flex-layout globals

---

src/lib/extended/img-src/img-src.spec.ts
src/lib/extended/img-src/img-src.ts

fix(img-src): correctly initialize fallback value

---

src/apps/demo-app/src/app/media-query-status/media-query-status.component.ts
src/apps/demo-app/src/app/responsive/responsive-row-column/responsive-row-column.component.ts
src/lib/core/add-alias.ts
src/lib/core/match-media/match-media.spec.ts
src/lib/core/match-media/match-media.ts
src/lib/core/media-change.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/core/media-observer/media-observer.ts
src/lib/core/public-api.ts
tslint.json

Previous versions of MediaObserver suffered from a significant design-flaw. 
Those versions assumed that a breakpoint change would only activate/match a single mediaQuery. Additionally those versions would not (by default) report overlapping activations. Applications interested in notifications for all current activations would therefore not receive proper event-notifications.
The current enhancements provide several features:
* Report 1..n mediaQuery activations (matches == true) in a single event
* Report activations sorted by descending priority
* By default, reports include overlapping breakpoint activations
* Debounce notifications to a single grouped event
> useful to reduce browser reflow thrashing
The stream data type is now **MediaChange[]** instead of …

fix(core): MediaObserver can report 1..n activations

---

src/lib/extended/class/class.spec.ts
src/lib/extended/class/class.ts

In cases where a fallback `ngClass` is not defined, the directive had
no way of knowing to remove its `ngClass` on deactivation because the
`removeStyles` method has no effect on `ngClass` (this is the default
for all other directives). By specifying an empty default fallback, we
ensure that on deactivation, if no other default is specified, the 
directive will correctly fallback to an empty string case.
Fixes #992

fix(ngClass): should properly remove classes without fallback

---

src/lib/core/match-media/index.ts
src/lib/core/public-api.ts
src/lib/extended/class/class.spec.ts
src/lib/extended/img-src/img-src.spec.ts
src/lib/extended/show-hide/hide.spec.ts
src/lib/extended/show-hide/show.spec.ts
src/lib/extended/style/style.spec.ts
src/lib/flex/flex-offset/flex-offset.spec.ts
src/lib/flex/flex-order/flex-order.spec.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout/layout.spec.ts
src/lib/grid/align-columns/align-columns.spec.ts
src/lib/grid/align-rows/align-rows.spec.ts
src/lib/grid/area/area.spec.ts
src/lib/grid/areas/areas.spec.ts
src/lib/grid/auto/auto.spec.ts
src/lib/grid/column/column.spec.ts
src/lib/grid/columns/columns.spec.ts
src/lib/grid/gap/gap.spec.ts
src/lib/grid/grid-align/grid-align.spec.ts
src/lib/grid/row/row.spec.ts
src/lib/grid/rows/rows.spec.ts
src/lib/server/server-match-media.ts
src/lib/server/server-provider.ts

* `MatchMedia` is no longer exported as a public utility. Please use `MediaObserver` instead. 
* `ServerMatchMedia` is no longer exported at all

feat(core): move MatchMedia to internal scope

---

src/lib/core/README.md
src/lib/core/match-media/match-media.ts
src/lib/core/match-media/mock/mock-match-media.ts
src/lib/core/media-trigger/index.ts
src/lib/core/media-trigger/media-trigger.spec.ts
src/lib/core/media-trigger/media-trigger.ts
src/lib/core/public-api.ts
src/lib/core/tokens/library-config.ts
src/lib/server/server-match-media.ts

The Windows MatchMedia API announces breakpoint activations during viewport resizing.
For some scenarios, developers need support for manual activations (without resizing). 
Such features are useful for:
* for SSR
* for designer environments 
> for immediate rendering of layouts for specific (1..n) breakpoints

feat(core): implement MediaTrigger to allow manual activations

---

src/lib/core/tokens/library-config.ts
src/lib/server/server-provider.ts

On the server, there is no conception of "browser window," because Angular's
browser implementation doesn't implement it. This means MatchMedia breakpoint activations will not work on the server. 
Layout SSR will generate CSS Stylesheets for all known breakpoints. And for the static, delivered-first HTML pages the directives are replaced with their associated, generated CSS classnames. 
But for programmatic usages of `MediaObserver`, we don't have a fallback mechanism to *announce* breakpoint activations. This PR allows a user to specify which activations they want to trigger via the MediaObserver for programmatic view listeners.
This can be done using the following configuration:
```ts
FlexLayoutModule.withConfig({serverBreakpoints: ['xs', 'lt-md']})
```
Fixes #991

feat(server): allow ability to specify breakpoints to activate on server

---

src/lib/core/breakpoints/data/break-points.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/core/sass/_layout-bp.scss

In rare cases, browsers resizing may create viewports with subpixel values.
Previous mediaQueries had 1 pixel gaps where the bounding ranges do not match.
Update the `max-width` values to include subpixel values and eliminate 99.99% of all gaps.
Fixes #1001.

fix(core): update breakpoint ranges to remove subpixel gaps

---

src/lib/core/breakpoints/data/break-points.ts
src/lib/core/breakpoints/data/orientation-break-points.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/core/media-observer/media-observer.ts
src/lib/core/sass/_layout-bp.scss
src/lib/core/utils/array.ts

* Ensure standard breakpoints mediaQueries are aligned with those in the CDK
* Update MediaObserver
* isActive() enhanced to support list of aliases to determine if any match
* properly disconnects subscribers when destroyed
The `@angular/cdk` BreakpointObserver will not replace `@angular/flex-layout` MediaObserver. **MediaObserver** is an enhanced version that notifies subscribers of activations for standard AND **overlapping (lt-xxx, gt-xxx)**  breakpoints.
> Note: Developers should use MediaObserver (not use MatchMedia) service to observe breakpoint activations! MediaObserver is the recommended service to use for application developers; MatchMedia should be considered a private service.
Fixes #685. Refs #1001.

update(core): align breakpoints with those used in CDK

---

README.md

I added a new **Getting Started** section to the `readme.md` file. I grabbed the data from the wiki combined with what I did this morning to include it into a project. I think having a spot on the readme makes it easier to find, and has become somewhat expected with other projects showing the base use case of getting up and running.

docs: add a Getting Started section to the README

---

src/lib/core/style-utils/style-utils.ts

Hi, we've been doing some research to find out why the flex layout library throws errors on older browsers. More specifically, Safari on iOS 8 and below. 
This issue reports about this error: https://github.com/angular/flex-layout/issues/958 - it says it's a duplicate of https://github.com/angular/flex-layout/issues/947, however, these errors seem slightly unrelated.
The problem is the `lookupStyle` method in the `StyleUtils` service calls `getComputedStyle(element).getPropertyValue(styleName)`. The spec says that `getPropertyValue` should return an empty string if the style is not set, however, on some older browsers it returns `null` instead. This causes an error when the method returns `value.trim()`, since value isn't a string.
This PR adds a safeguard to check for `null` and makes …

Fail-safe handling of nullable string value in lookupStyle

---

src/lib/flex/layout-align/layout-align.spec.ts
src/lib/flex/layout-align/layout-align.ts

fix(layout-align): respect inline-flex on sibling fxLayout

---

src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout-gap/layout-gap.ts

fix(fxLayoutGap): correctly handle lack of fallback value

---

src/lib/flex/flex/flex.ts
src/lib/flex/layout-align/layout-align.spec.ts

fix(fxFlex): restore correct styles after fxLayoutAlign is applied

---

src/lib/core/breakpoints/data/break-points.ts
src/lib/core/breakpoints/data/orientation-break-points.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/core/sass/_layout-bp.scss

In Chrome, .99 is treated as 1 which cause ranges to overlap at the exact breakpoint.
> Note: the behavior might not be considered as a bug in chrome as in [W3 specifications](https://www.w3.org/TR/mediaqueries-4/#mq-min-max) it's mentioned that for sub-pixels or fractions it's preferred to use [the not widely supported range context](https://www.w3.org/TR/mediaqueries-4/#range-context).
Fixes angular/flex-layout#1052. Affects angular/flex-layout#1001.

fix(core): update breakpoint ranges to avoid overlapping

---

src/lib/server/server-match-media.ts
src/lib/server/server-provider.ts

MediaObserver on the server was not observing the breakpoints at the same lifecycle as the browser. This change moves the active breakpoints check from `BEFORE_APP_SERIALIZED` to the `ServerMatchMedia` service.

fix(server): breakpoints can be used by MediaObserver

---

src/lib/flex/flex/flex.ts

fix(fxFlex): use correct type for basis validation in reflow case

---

.github/workflows/lock-closed.yml

Now that the backlog of inactive closed issues/prs has been locked, we should only run the action once per day.

ci: update lock-closed to only run once per day

---

src/lib/package.json

We no longer directly have a direct depedency on `tslib`. Instead it is now listed a `peerDependency`.
Users not using the CLI will need to manually install `tslib` via;
```
yarn add tslib
```
or
```
npm install tslib --save
```
Reference: TOOL-836

feat: change tslib from direct dependency to peerDependency

---

src/lib/core/media-marshaller/print-hook.ts

Extends the PrintHook service to also register beforeprint and afterprint event handlers to synchronously update styles and prevent layout switching races.
The PrintHook service was good at handling show/hide but layout changes between row/column were having many race issues and more often than not they were not working while printing due to the underlying `matchMedia` api being async.
Related #603
See https://github.com/angular/flex-layout/issues/603#issuecomment-499362799 for proposal and more info.
CC @CaerusKaru @ThomasBurleson
----
The main issue I had figuring this out was actually the deactivation of printing and getting the PrintHook service to restore the original media queries. I ended up figuring out a bit how the deactivations are stored and that essentially the following …

feat(core): support beforeprint and afterprint hooks

---

src/lib/server/server-provider.ts

Previously, the unique class generation routine used a
local variable to keep track of individual elements.
However, this counter would never get reset, meaning
that it would get incremented on each subsequent
server render, leading to enormous values for the class
names, erroneously. This resets the counter to zero for
each render.

fix(ssr): reset class counter to zero before each render

---

tools/package-tools/build-bundles.ts

The APF specification does not capture all corner cases, but conceptually,
generated UMD bundles should match the actual entry-point in the typings tree.
This means that it's technically spec-compliant to include secondary entry-points in a
primary UMD bundle. At the same time though, it's also spec-compliant to not include
secondary entry-points and require UMD consumers to load the secondary entry-point
UMD bundles manually. 
We are going with the latter since that helps with an issue that has surfaced in ngcc.
The plan is to update the APF specification to explicitly guard against cases like that,
so that primary UMD bundles no longer can bundle secondary entry-points. This
change prepares flex-layout for the change to the APF specification.

build: do not include secondary entry-points in primary UMD bundle

---

src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.ts
src/lib/flex/layout-gap/layout-gap.spec.ts
src/lib/flex/layout-gap/layout-gap.ts

This allows users to specify different options for X and Y gaps.
The default is to apply the value to both X and Y, which is the
current behavior.
Fixes #1229

feat(layout-gap): add x/y options for grid mode

---

src/lib/core/base/base2.ts
src/lib/core/style-utils/style-utils.ts
src/lib/flex/flex/flex.spec.ts
src/lib/flex/flex/flex.ts

When the element itself is initialized within an NgForOf element,
previously the Flex direction initialization would take place too
early. As a result, the directive would not update on parent
changes correctly. This commit corrects this by adding the
initialization logic into OnInit.
Fixes #1160

fix(flex): wait for parent element until template is initialized

---

docs/documentation/fxFlex-API.md

The divider elements was not closed correctly

docs: fix HTML closing tags for fxFlex API page

---

package.json

CI is failing nondeterministically when it runs out of memory
running ngcc.
Closes #1180

build: use no async option for ngcc

---

src/lib/extended/show-hide/show-hide.ts
src/lib/extended/show-hide/show.spec.ts

When SSR creates media screen styles, it sets the default `display`
CSS property to `parent.display`. However, if the parent has its
`display` property unset, it results in an empty display that breaks
the correct functionality as the next closest match is made.
This is fixed by setting `display` to `initial` as default instead
of an empty value.
Credit to @vmasek
Fixes #1163
Closes #1168

fix(show-hide): use initial value as fallback instead of parent

---

src/lib/core/match-media/match-media.ts
src/lib/core/media-observer/media-observer.spec.ts
src/lib/core/media-observer/media-observer.ts

Previously, only triggering `MatchMedia.observe` would correctly
register media queries for later usage in the `MediaObserver`.
This is incorrect, and queries should be registered if a) they
are valid breakpoints in Angular Layout, and b) they are not
currently registered.
Fixes #1025

fix(media-observer): return correct value for isActive on init

---

src/lib/core/media-marshaller/media-marshaller.ts
src/lib/extended/class/class.spec.ts

In certain cases, users may need to dynamically set the value of
an input to `undefined`. This value should then be ignored in
place of another value in the fallback mechanism.
Fixes #1207

fix(media-marshaller): do not propagate undefined value

---

src/lib/core/base/base2.ts

This is a performance enhancement to ensure that DOM changes are
only triggered if and when a value for a directive actually
changes.
Fixes #1083

fix(core): only trigger style updates when value changes

---

src/lib/core/media-marshaller/media-marshaller.ts

Previously we only ignored `undefined`, now we ignore `null` too.

fix(core): ignore null values in breakpoint fallback mechanism

---

src/lib/core/match-media/match-media.ts
src/lib/core/media-trigger/media-trigger.spec.ts
src/lib/core/media-trigger/media-trigger.ts

When the internal registry of media query listeners is reset, or
MatchMedia is destroyed, the listeners themselves are not currently
being removed. This leads to memory leaks, which is corrected by
this commit.
Fixes #1213

fix(match-media): unregister media query event listeners on destroy

---

src/lib/extended/show-hide/show-hide.ts
src/lib/extended/show-hide/show.spec.ts

In the event that a user specifies two breakpoints with conflicting
show/hide, e.g. fxHide.lt-lg and fxShow.md, fxShow will not be
able to re-enable CSS `display`, since there's no equivalent to
nulling out the styles, which is what we do when handling it
inline in the browser.
This sets the property to `initial` in SSR stylesheets only. This
should preserve browser behavior where nulling out the styles still
works.
NOTE: if you have other classes that set the `display` property of
an element, they may get overridden in SSR only. This is
unavoidable, since getComputedStyle is not available to use in SSR.
Fixes #1250

fix(show-hide): set explicit display fallback for SSR

---

src/lib/module.ts

In Angular v10, ModuleWithProviders generic typing is no longer
optional. To prepare for this, the correct typing is added.

fix(core): add generic type to ModuleWithProviders to support v10

---

src/lib/core/match-media/mock/mock-match-media.spec.ts
src/lib/core/match-media/mock/mock-match-media.ts

Previously overlapping (lt, gt) breakpoints were not being
registered when overlapping activations were set. This commit
registers all breakpoints when they are supposed to be activated,
if they are not already.
Fixes #1263

fix(mock-match-media): ensure overlapping breakpoints are activated

---

tools/tslint-rules/noRxjsPatchImportsRule.ts
tools/tslint-rules/noViewEncapsulationRule.ts
tools/tslint-rules/validateDecoratorsRule.ts

Remove usage of the term whitelist in commenting for noRxjsPatchImportsRule,
noViewEncapsulationRule and validateDecoratorRule.

build: update tslint rules to remove usage of whitelist in comments

---

src/lib/core/breakpoints/data/break-points.ts
src/lib/core/breakpoints/data/orientation-break-points.ts
src/lib/core/match-media/mock/mock-match-media.spec.ts
src/lib/core/media-observer/media-observer.spec.ts

Setting the breakpoint value to .9 leads the browser to incorrectly
round-up and cause overlap with fractional pixels and their
upper bound. This leads to unintended consequences in downstream
consumers like our MediaObserver and MatchMedia providers.

fix(core): set fractional breakpoints to .98 instead of .9

---

CHANGELOG.md
package.json
yarn.lock

chore: update to 13.0.0-beta.36 with changelog

---

projects/libs/flex-layout/core/base/base2.ts
projects/libs/flex-layout/core/media-marshaller/media-marshaller.ts
projects/libs/flex-layout/flex/layout/layout.spec.ts

When a directive is fired, it sets a current value to compare to
future values, that way we don't fire mutiple costly element
change events per media update. However, when a directive moves
to an "uncovered" segment, ie a segment where there is no active
value, we are not clearing the previous current value. This leads
to a lack of updates when styles are not present but should be,
e.g. when a directive moves into an uncovered segment, and then
back into a covered one.
Therefore, we reset the currentValue for a directive when we clear
styles, to enable updates when moving back to a covered segment
later.
Fixes #1291

fix(core): reset current value when directive is cleared

---

projects/libs/flex-layout/core/match-media/mock/mock-match-media.ts
projects/libs/flex-layout/core/media-marshaller/media-marshaller.ts
projects/libs/flex-layout/core/media-observer/media-observer.spec.ts
projects/libs/flex-layout/core/media-observer/media-observer.ts

It is unfortunately the case in a real-world browser environment
that overlapping breakpoints trigger separate events in our change
monitoring schema. This is (nearly) unavoidable, but what we can
do is ensure that we only emit distinct events for our event
aggregator, MediaObserver. We now only emit when we get an entirely
distinct set of media changes from the previous state.
Fixes #1041

fix(core): only emit changed events from MediaObserver

---

projects/libs/flex-layout/core/media-marshaller/media-marshaller.spec.ts
projects/libs/flex-layout/core/media-marshaller/media-marshaller.ts
projects/libs/flex-layout/core/media-marshaller/print-hook.ts

During print events, we assign the activated breakpoints array
by reference, and then clear that same array. This means that the
activated breakpoints are not restoring correctly. Instead, make
sure we make a new array reference that cannot be polluted the
same way.
Fixes #1201

fix(core): correctly set and restore breakpoints during print

---

projects/libs/flex-layout/core/media-marshaller/media-marshaller.ts
projects/libs/flex-layout/core/media-marshaller/print-hook.ts

Previously we were collecting all deactivating breakpoints before
a print event. The problem with this, of course, is that our
breakpoints are designed as "screen and", which means that
transitioning to a new device type, in this case "print" sends out
deactivating media query events for _all_ of our breakpoints. This
means that our collection was useless because we were essentially
saying deactivate and then restore all breakpoints.
This corrects this behavior by doing two things:
1. If the print media query has not fired, use the activated
breakpoints from the marshaller to decide if the breakpoint
even needs to be deactivated
2. If the print media query has been fired, check a snapshot of
the most recent activations to determine if a breakpoint needs to
be deactivated.
Since we can't …

fix(core): properly collect deactivated breakpoints before print

---

projects/libs/flex-layout/core/multiply/multiplier.ts
projects/libs/flex-layout/core/public-api.ts
projects/libs/flex-layout/core/tokens/library-config.ts
projects/libs/flex-layout/flex/flex-offset/flex-offset.spec.ts
projects/libs/flex-layout/flex/flex-offset/flex-offset.ts
projects/libs/flex-layout/flex/layout-gap/layout-gap.spec.ts
projects/libs/flex-layout/flex/layout-gap/layout-gap.ts

It may be desirable for users to multiply the base values to keep
some sort of internal consistency. For instance, in Material
Design, values are typically multiplied by 4x or 8x. To support
this, we add a new configuration option to the library that plugs
in to select directives (at this point, only `fxFlexOffset` and
`fxLayoutGap`). To use this feature, use the following syntax:
```ts
@NgModule({
imports: [
FlexLayoutModule.withConfig({
multiplier: {
value: 4,
unit: 'px',
}
}),
],
})
export class MyAppModule {}
```
```html
<div fxFlexOffset="3x">My content</div>
```
This yields:
```html
<div style="margin-right: 12px">My content</div>
```
This feature is disabled by default, so to use it, you must
explicitly specify both the value and unit of your multiplication.
Fixes #907

feat(core): add value multiplication suffix feature

---

projects/libs/flex-layout/core/tokens/library-config.ts
projects/libs/flex-layout/flex/layout-gap/layout-gap.spec.ts
projects/libs/flex-layout/flex/layout-gap/layout-gap.ts

If a user specifies a value for a directive without a unit, either
intentionally or otherwise, we currently error out for most cases.
Therefore, we introduce a config option that by default appends
a unit to unitless values. The built-in default is `px`, but could
just as easily be set to `%` or `vh` depending on a user's app.
Currently, the only supported directive for this feature is
`fxLayoutGap`, but _not_ in `grid` mode.
To use, follow this syntax:
```ts
@NgModule{{
imports: [
FlexLayoutModule.withConfig({defaultUnit: '%'}),
],
})
export class MyAppModule {}
```
Then use the following HTML:
```html
<div fxLayoutGap="5">
<div>Line one</div>
<div>Line two</div>
</div>
```
This would result in the following markup:
```html
<div fxLayoutGap="5">
<div style="margin-right: 5%">Line …
```

feat(core): add support for default unit for unitless values

---

projects/libs/flex-layout/_private-utils/layout-validator.ts
projects/libs/flex-layout/core/style-utils/style-utils.ts
projects/libs/flex-layout/core/tokens/library-config.ts
projects/libs/flex-layout/flex/layout/layout.spec.ts
projects/libs/flex-layout/flex/layout/layout.ts

In some cases, a user may intentionally hide a directive using
styling that exists outside of the scope of this library. However,
fxLayout had no way of detecting this, or establishing a precedence
for pre-existing styles. This adds detection and special caching
for pre-styled display attributes on an element. This means that if,
at any point in the change detection of the directive for its entire
lifespan, it detects that the style has been set to `display: none`,
it will use that as the display value in place of what it otherwise
would have used.
Please note: this means that you need to be more careful when using
this functionality! If, for instance, you have functionality that
sets `display: none` on a directive, that functionality needs to
now take over restoring the correct style for …

feat(flex): detect display precedence in fxLayout directive

---

projects/libs/flex-layout/core/media-observer/media-observer.ts

RxJS x7 supports top-level exports, but since we still support
RxJS v6, we need to continue to import from the operators
subexport.
Fixes #1389

fix(core): import distinctUntilChanged from rxjs/operators

---

projects/libs/flex-layout/core/add-alias.ts
projects/libs/flex-layout/core/media-observer/media-observer.spec.ts
projects/libs/flex-layout/core/media-observer/media-observer.ts

This feature has been deprecated and slated for removal for
several versions. Instead, please use MediaObserver::asObservable.
Note that the usage of this feature has changed, as individual
values are no longer emitted, instead favoring emitting
a full change set.
* MediaObserver::media$ has been removed. Please use
MediaObserver::asObservable instead.

feat(core): remove deprecated MediaObserver::media$

---

projects/libs/flex-layout/_private-utils/auto-prefixer.ts

When we clear styles on the server, we emit an empty value in
order to flush the cache. However, all values still end up
passing through the auto-prefixer, which then converted this
value to the default value of row. However, other components
own the default 'row' value fallback, and so this only serves
to add another layer of logic that gets in the way. Now, we remove
it so that the overlying mechanisms can work as intended in both
browser and server.
Fixes #1394

fix(private): remove fallback from flex-direction auto-prefixer
